# ---- build stage (переиспользуем общий)
FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o bin/ProcessService ./ProcessService

# ---- runtime stage
FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/bin/ProcessService ./ProcessService

CMD ["./ProcessService"]