# ---- build stage
FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git
RUN go install github.com/swaggo/swag/cmd/swag@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN swag init -g cmd/server/main.go -o docs/
RUN go build -o bin/server  ./cmd/server

# ---- runtime stage
FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/bin/server   ./server
COPY --from=builder /app/docs/        ./docs/

EXPOSE 8080

CMD ["./server"]